- name: Install homeassistant websocket node.js package
  become: true
  community.general.npm:
    name: node-red-contrib-home-assistant-websocket
    global: yes
    
- name: Create nodered persistant data dir
  become: true
  ansible.builtin.file:
    path: "{{ docker_dir }}/nodered/data"
    state: directory
    owner: '1000'
    group: '1000'
    mode: '0755'

- name: Copy the compose file
  become: true
  template:
    src: templates/compose.yaml
    dest: "{{ docker_compose_dir }}/compose.nodered.yaml"
  notify: start nodered

- name: Flush handlers #force preceeding handler to run immediately
  meta: flush_handlers

- name: Ensure Node.js and npm are installed.
  become: true
  apt:
    name: 
    - nodejs
    - npm
    state: present
