- name: start nodered
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    files:
    - compose.nodered.yaml

- name: restart nodered
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    files:
    - compose.nodered.yaml
    state: restarted
